# Generated by Django 3.0.2 on 2020-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('purchase_price', models.PositiveIntegerField()),
                ('depreciation_rate', models.FloatField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-purchase_price'],
            },
        ),
    ]
