# Generated by Django 3.0.2 on 2020-05-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_account_payee_transaction_transactioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='available_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
