# Generated by Django 3.0.2 on 2020-05-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_account_available_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('C', 'Cash'), ('B', 'Bank'), ('M', 'Mobile'), ('D', 'Deposit')], default='B', max_length=2),
        ),
    ]
