# Generated by Django 3.0.2 on 2020-05-17 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200517_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='transactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='dashboard.Transaction'),
        ),
    ]
