# Generated by Django 3.0.2 on 2020-05-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_account_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='transactions',
        ),
        migrations.AddField(
            model_name='account',
            name='transactions',
            field=models.ManyToManyField(related_name='transaction', to='dashboard.Transaction'),
        ),
    ]
