# Generated by Django 3.0.2 on 2020-05-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_transaction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Category')),
            ],
            options={
                'verbose_name': 'Transaction category',
                'verbose_name_plural': 'Transaction categories',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='dashboard.Service'),
        ),
        migrations.DeleteModel(
            name='TransactionCategory',
        ),
    ]
