# Generated by Django 3.0.2 on 2020-05-17 14:48

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
