# Generated by Django 3.0.2 on 2020-05-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200517_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
