# Generated by Django 3.0.2 on 2020-05-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='transaction', to='dashboard.Transaction'),
        ),
    ]
