# Generated by Django 3.0.2 on 2020-05-18 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0018_auto_20200518_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('role', models.CharField(blank=True, max_length=20, null=True, verbose_name='Employee Duties')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Employee salary')),
                ('employment_type', models.CharField(blank=True, choices=[('CON', 'Contract'), ('CAS', 'Casual worker')], default='CAS', max_length=3, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateField(verbose_name='Employee payment date')),
                ('other_info', models.TextField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['salary'],
            },
        ),
    ]
