# Generated by Django 3.0.2 on 2020-05-19 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='on_payroll',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Account'),
        ),
    ]
