# Generated by Django 3.0.2 on 2020-05-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20200522_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransafer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('ref_number', models.CharField(blank=True, max_length=20, null=True)),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_account', to='dashboard.Account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_account', to='dashboard.Account')),
            ],
        ),
    ]
