# Generated by Django 3.0.2 on 2020-05-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_accounttransafer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountTransafer',
            new_name='AccountTransfer',
        ),
    ]
