# Generated by Django 3.0.2 on 2020-05-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20200526_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransfer',
            name='from_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_account', to='dashboard.Account'),
        ),
        migrations.AlterField(
            model_name='accounttransfer',
            name='to_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_account', to='dashboard.Account'),
        ),
    ]
